name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unset ANDROID_HOME
        run: echo "ANDROID_HOME=" >> $GITHUB_ENV
      - name: Run gradle build
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: android
          args: assemble_release
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
